- components/composed/model/ModelGrid/ModelGridItem.tsx
- components/composed/model/helpers/columns.tsx
- components/composed/model/plugins/useRowActions.tsx
- components/global/AppBody/styles.ts
- components/layout/Grid/Grid.stories.tsx
- components/layout/Grid/Grid.styles.ts
- components/layout/Grid/Grid.tsx
- components/layout/PageCountActions/PageCountActions.styles.ts
- components/layout/Table/Table.styles.ts
- components/layout/Table/TableBody.tsx
- components/layout/Table/TableCell.tsx
- theme/base/resets.ts
- theme/base/variables.ts
- theme/mixins/appearance.ts
- theme/mixins/typography.ts
- theme/utility/typography.ts
- types/react-table-config.d.ts
- Add labels to meta data in grid view 
- Style table item link the same as grid
- Allow some cells to be truncated
- Align table actions to the right
TODO:
~Actions should roll up into an ellipsis button on mobile~ Going to make a separate issue for this
> [F] Grid and Table improvements

- components/api/QueryWrapper.tsx
Without this change, navigating between two routes that share the
component but have different URL params would not necessitate reloading
data for the new route.
> [B] QueryWrapper will refetch when vars change

- hooks/index.ts
- hooks/useBaseListQueryVars.ts
- pages/collections/[slug]/collections.tsx
- pages/collections/[slug]/items.tsx
- pages/collections/index.tsx
- pages/communities/[slug]/collections.tsx
- pages/communities/index.tsx
- pages/contributors/[slug]/collections.tsx
- pages/contributors/[slug]/details.tsx
- pages/contributors/[slug]/items.tsx
- pages/contributors/index.tsx
- pages/items/index.tsx
- pages/users/index.tsx
The problem:
Pagination and ordering are not working as expected. Both should be controlled using URL query parameters, so that links to a specific page and order can be shared. Currently clicking on next page or an order does nothing.
This PR fixes the issue by getting the query params from the router and passing them to QueryWrapper. There needs to be a little further refactoring to prevent the page from reloading everything (header, search bar, etc) when getting new items.
BUT! I noticed there is a `setVariables` method getting passed from QueryWrapper to its children. It's currently not used in any lists. 
I want to make sure I'm not stepping on anyone's toes here before I make further changes. Are we all on the same page for using the URL query to search, sort, and paginate the list?
> [B] Fix pagination

- package.json
This flag disabled webpack optimization.sideEffects. See:
https://webpack.js.org/configuration/optimization/#optimizationsideeffects
Without setting this flag, Storybook is failing to import modules
properly. It's unclear why this flag resolves the problem, so this may
only be an interim fix.
> [B] Address storybook failed imports

- components/atomic/SidebarNav/SidebarNav.tsx
- components/composed/collection/CollectionLayout/CollectionLayout.tsx
- components/composed/community/CommunityLayout/CommunityLayout.tsx
- components/composed/contributor/ContributorLayout/ContributorLayout.tsx
- components/composed/item/ItemLayout/ItemLayout.tsx
- components/composed/user/UserLayout/UserLayout.tsx
- components/layout/PageHeader/PageHeader.tsx
- locales/en.json
- pages/contributors/[slug]/collections.tsx
- pages/contributors/[slug]/items.tsx
- routes/baseRoutes.ts
@jen-castiron and @1aurend — I went ahead and implemented these secondary headers in the layouts, building on your changes to PageHeader. Please feel free to adjust the approach in this PR in a subsequent commit if you're not happy with it. I just wanted these looking good for the demo tomorrow, and it only took a few minutes to get them in place.
> [F] Add secondary headers to layouts

- components/composed/collection/CollectionList/CollectionList.tsx
- components/composed/community/CommunityList/CommunityList.tsx
- components/composed/contribution/CollectionContributionList/CollectionContributionList.tsx
- components/composed/contribution/ItemContributionList/ItemContributionList.tsx
- components/composed/contributor/ContributorList/ContributorList.tsx
- components/composed/item/ItemList/ItemList.tsx
- components/composed/model/ModelListHeader/ModelListHeader.tsx
- components/composed/model/ModelListPage/ModelListPage.tsx
- components/composed/user/UserList/UserList.tsx
@jen-castiron I think these props are correct now, except `ModelListPage`. Which type there do I extend to add the header props? I have this, which I don't think is right:
```
type ModelListPageProps<
T extends OperationType,
U extends PaginatedConnectionish,
V extends Record<string, unknown> = Record<string, unknown>
> = Omit<ModelListProps<T, U, V>, "view"> &
Pick<ModelListActionsProps, "viewOptions"> &
Pick<HeaderProps, "headerStyle" | "hideHeader"> & {
defaultView?: ModelListActionsProps["active"];
buttons?: ReactNode;
};
```
> [C] DRY PageHeader props

- components/composed/community/CommunityLayout/CommunityLayout.tsx
- components/composed/contributor/ContributorLayout/ContributorLayout.tsx
- components/composed/user/UserLayout/UserLayout.tsx
- components/factories/IconFactory/IconFactory.tsx
- components/layout/BackToAll/BackToAll.stories.tsx
- components/layout/BackToAll/BackToAll.styles.ts
- components/layout/BackToAll/BackToAll.tsx
- components/layout/BackToAll/index.ts
- components/layout/PageHeader/PageHeader.tsx
- components/layout/index.ts
- locales/en.json
- routes/baseRoutes.ts
After discussing the problem with the FE team, the consensus was that it's OK to have both breadcrumbs on models with parent/child relationships and a "back" link on other models. Collections and Items are easy to get back to, as their link is provided in the main nav. (While "contributors" is hidden behind a dropdown).
Having just the text "Contributors" didn't seem like enough context for the user:
Adding an arrow and extra text seemed to help distinguish this back button from the parent/child breadcrumbs on other pages:
There's one more problem. If I land on a contributor page from an item or collection, going "Back to Contributors" doesn't make sense. It would make more sense to say "Back to [Item Name]". Unfortunately `next/router` does not provide a way to get the last route, so we …
> [F] Add back link to pages without clear parent child relationships

- components/layout/Modal/Modal.stories.tsx
- components/layout/Modal/Modal.styles.ts
- components/layout/Modal/Modal.tsx
- components/layout/Modal/index.ts
This Modal component is based largely off Drawer. It includes a simplified header and the remainder of its content is rendered in its children. Eventually, `dialog.hide` will need to be passed to the children so buttons can close the modal.
> [F] Create Modal layout component

- components/atomic/buttons/ButtonControl/index.ts
- components/atomic/buttons/ButtonControl/patterns/ButtonControlDrawer.stories.tsx
- components/atomic/buttons/ButtonControl/patterns/ButtonControlDrawer.tsx
- components/atomic/buttons/ButtonControlGroup/ButtonControlGroup.stories.tsx
- components/atomic/buttons/ButtonControlGroup/ButtonControlGroup.tsx
- components/atomic/buttons/index.ts
- components/composed/contributor/ContributorList/ContributorList.tsx
- components/global/Header/HeaderNavLinks.tsx
Created a new ButtonControl pattern called ButtonControlDrawer. As the name suggestions, this is a button control that opens a drawer! Creating a pattern made it easer to add the drawer flag to the ButtonControlGroup.
For everyone's sake, here's the difference between each control:
* ButtonControl - A styled button. Can be a link if `as='link'` prop is passed
* ButtonControlDrawer - A button control that opens a drawer. Uses DrawerLink and ButtonControl under the hood.
* ButtonControlGroup - Pass in an array of button props, and this spits out a list of button controls. On mobile, the controls are in a dropdown menu.
> [F] Add drawer option to ButtonControlGroup 

- components/composed/model/ModelColumns/NameColumn.tsx
- components/composed/model/ModelGrid/ModelGridItem.tsx
@jen-castiron This was literally a one-letter fix, but I wanted to flag that problem was matching a case sensitive string in case we want to do more to make these consistent. "Name" seems to be the only `id` value that's capitalized.
> [B] Remove name label from grids

- components/atomic/buttons/ButtonControlGroup/ButtonControlGroup.stories.tsx
- components/atomic/buttons/ButtonControlGroup/ButtonControlGroup.tsx
- components/atomic/dropdown/Dropdown/Dropdown.tsx
- components/composed/community/CommunityList/CommunityList.tsx
- components/composed/contribution/CollectionContributionList/CollectionContributionList.tsx
- components/composed/contribution/ItemContributionList/ItemContributionList.tsx
- components/composed/contributor/ContributorList/ContributorList.tsx
- components/composed/file/FileList/FileList.tsx
- components/composed/model/ModelList/hooks/useRowActions.tsx
- components/layout/Grid/Grid.stories.tsx
This PR simplifies `ButtonControlGroup` so that it no longer needs to know the possible types of its children. Rather than taking a prop object with options and creating `ButtonControl` children inside `ButtonControlGroup`, the group now accepts children of the various button control patterns and is only responsible for determining whether to render a row of buttons or a dropdown.
Usage:
```
<ButtonControlGroup>
<ButtonControl>A plain button</ButtonControl>
<ButtonControlDrawer icon="edit" drawer="...">A drawer button, like edit</ButtonControlDrawer>
<ButtonControlConfirm icon="delete" modalBody="...">A confirmation button, like delete</ButtonControlConfirm>
</ButtonControlGroup>
```
Note: `useRowActions` was modified to create button children rather than the `buttonProps` object for this …
> [C] Refactor ButtonControlGroup to reduce complexity

- __generated__/EntityLinksListFragment.graphql.ts
- __generated__/EntityOrderingAddDrawerQuery.graphql.ts
- __generated__/EntityOrderingAddFormFragment.graphql.ts
- __generated__/EntityOrderingAddFormMutation.graphql.ts
- __generated__/EntityOrderingListDataFragment.graphql.ts
- __generated__/EntityOrderingListFragment.graphql.ts
- __generated__/linksManageCollectionsPagesQuery.graphql.ts
- __generated__/linksManageSlugItemsQuery.graphql.ts
- __generated__/orderManageSlugOrderingsPagesQuery.graphql.ts
- __generated__/ordersManageSlugItemsQuery.graphql.ts
- components/composed/links/EntityLinksList/EntityLinksList.tsx
- components/composed/ordering/EntityOrderingAddDrawer/EntityOrderingAddDrawer.tsx
- components/composed/ordering/EntityOrderingAddDrawer/index.ts
- components/composed/ordering/EntityOrderingAddForm/EntityOrderingAddForm.tsx
- components/composed/ordering/EntityOrderingAddForm/index.ts
- components/composed/ordering/EntityOrderingList/EntityOrderingList.tsx
- components/forms/RadioGroup/RadioGroup.tsx
- components/forms/index.ts
- hooks/useDrawerHelper.ts
- pages/collections/[slug]/manage/links.tsx
- pages/collections/[slug]/manage/order.tsx
- pages/items/[slug]/manage/links.tsx
- pages/items/[slug]/manage/order.tsx
Adds the form for adding a dynamic ordering to a collection or item.
Note: This form is waiting for the query for order-able schema properties. No button to access it is visible in the UI.
> [F] Add dynamic ordering form

- package.json
- packages/admin/components/atomic/Breadcrumbs/Breadcrumb.stories.tsx
- packages/admin/components/atomic/Pagination/Pagination.stories.tsx
- packages/admin/components/atomic/links/NamedLink/NamedLink.stories.tsx
- packages/admin/package.json
- packages/admin/theme/stories/appearance.stories.tsx
- packages/admin/theme/stories/colors.stories.mdx
- packages/admin/theme/stories/layout.stories.tsx
- packages/admin/theme/stories/typography.stories.tsx
- yarn.lock
The deploy was using a higher version of common-js Breadcrumbs that had some breaking changes. For now, this sets the common-js breadcrumbs package to a specific version. We should eventually upgrade to version 1.0.0, or not use common-js breadcrumbs.
> [B] Fix breadcrumbs in storybook

- packages/admin/components/composed/ordering/EntityOrderingAddForm/EntityOrderingAddForm.tsx
- packages/admin/components/forms/RadioGroup/Radio.tsx
- packages/admin/components/forms/RadioGroup/RadioGroup.tsx
- Removed "none" option (UX decision - doesn't make sense to not have children to order)
- Fixed radio erroring if changed after submit by flattening `select.direct` object to `selectDirect`
- Fixed radio value by passing react-hook-form's register ref down to the Radio's input element
- Removed controlled selected/checked attributes on Radio (these are already handled by react-hook-form)
- Removed aria-checked from Radio (shouldn't be needed since we're using a radio input)
- Removed tab index from Radio (letting the browser handle the radio's keyboard navigation)
- Removed undefined default values
> [B] Fix entity radio group

- packages/admin/__generated__/EntityOrderingAddDrawerQuery.graphql.ts
- packages/admin/__generated__/EntityOrderingAddFormFragment.graphql.ts
- packages/admin/components/composed/ordering/EntityOrderingAddForm/EntityOrderingAddForm.tsx
- packages/admin/components/forms/RadioGroup/Radio.tsx
- packages/admin/components/forms/RadioGroup/RadioGroup.stories.tsx
- packages/admin/components/forms/RadioGroup/RadioGroup.tsx
- packages/admin/locales/en.json
Combines `Collections` and `Items` inputs to a single `Entities to Include` input. Creates `identifier` as a slug based on `displayName`. Removes `filter`.
> [F] Simplify dynamic ordering form select inputs

- packages/admin/.env
- packages/admin/components/atomic/buttons/ButtonControl/index.ts
- packages/admin/components/atomic/buttons/ButtonControl/patterns/ButtonControlView.tsx
- packages/admin/components/composed/collection/CollectionLayout/CollectionLayout.tsx
- packages/admin/components/composed/collection/CollectionList/CollectionList.tsx
- packages/admin/components/composed/community/CommunityLayout/CommunityLayout.tsx
- packages/admin/components/composed/community/CommunityList/CommunityList.tsx
- packages/admin/components/composed/item/ItemLayout/ItemLayout.tsx
- packages/admin/components/composed/item/ItemList/ItemList.tsx
- packages/admin/components/composed/model/ModelList/hooks/useModelList.tsx
- packages/admin/components/composed/model/ModelList/hooks/useRowActions.tsx
- packages/admin/locales/en.json
Adds "View" links to the admin app and a NEXT_PUBLIC_FE_URL env variable. Clicking on this link will open the community, collection, or item in the frontend app. To change the link to your dev environment, add an `.env.local` file to `packages/admin`, and change the NEXT_PUBLIC_FE_URL to `http://localhost:3001`
> [F] Add view button to admin app

- packages/frontend/components/composed/article/RelatedArticles/RelatedArticles.styles.ts
- packages/frontend/components/composed/article/RelatedArticles/RelatedArticles.tsx
Determined that there's no general way to determine when borders should be applied to .a-bg-custom10 elements and added border logic back to RelatedArticles.
> [C] Add top border to RelatedArticles

- packages/admin/components/api/SchemaInstanceForm/Properties/ScalarProperty/ScalarProperty.tsx
- packages/admin/components/api/SchemaInstanceForm/SchemaInstanceProvider.tsx
- packages/admin/components/forms/Fieldset/Fieldset.stories.tsx
- packages/admin/components/forms/FieldsetSection/FieldsetSection.stories.tsx
- packages/admin/components/forms/FileUpload/FileUpload.stories.tsx
- packages/admin/package.json
- packages/frontend/package.json
- packages/lib/package.json
- yarn.lock
- Remove `required` from register in ScalarProperty
- Remove `react-hook-form` dependency from lib and frontend packages
- Set `react-hook-form` to version 7.12.2
- Add boolean `watchInConsole` prop to SchemaProvider to turn on/off prop watcher
> [B] Fix issues with react-hook-form implementation

- packages/admin/components/forms/FullTextInput/FullTextInput.tsx
- packages/admin/pages/items/[slug]/manage/details.tsx
- packages/frontend/components/composed/article/ArticleText/AnchorElement.tsx
- packages/frontend/components/composed/article/ArticleText/ArticleText.styles.ts
- packages/frontend/components/composed/article/ArticleText/ArticleText.tsx
- packages/frontend/package.json
- packages/frontend/tsconfig.json
- packages/lib/helpers/strings.ts
- Currently blocked by an issue saving the FullTextProperty `body` on articles. Kind is always set to "TEXT".
- Fixes an issue with missing translations on backend when saving item schemas
> [F] Add content headers to article TOC

- packages/admin/__generated__/EntityLinksAddFormMutation.graphql.ts
- packages/admin/__generated__/EntityTitleFactoryFragment.graphql.ts
- packages/admin/__generated__/LinkTargetTypeaheadFragment.graphql.ts
- packages/admin/__generated__/LinkTargetTypeaheadQuery.graphql.ts
- packages/admin/__generated__/getEntityTitleFragment.graphql.ts
- packages/admin/components/composed/links/EntityLinksAddForm/EntityLinksAddForm.tsx
- packages/admin/components/factories/EntityTitleFactory/EntityTitleFactory.tsx
- packages/admin/components/factories/EntityTitleFactory/getEntityTitle.ts
- packages/admin/components/factories/EntityTitleFactory/index.ts
- packages/admin/components/factories/index.tsx
- packages/admin/components/forms/BaseTypeahead/BaseTypeahead.tsx
- packages/admin/components/forms/LinkTargetTypeahead/LinkTargetTypeahead.tsx
Try adding a link to view the updated names: [https://wdp-admin-git-jw-wdp-565-entity-ambiguity-cast-iron.vercel.app/collections/Gbmp657cxaQKTBdnF8BGDtrwG3GOenb/manage/links](https://wdp-admin-git-jw-wdp-565-entity-ambiguity-cast-iron.vercel.app/collections/Gbmp657cxaQKTBdnF8BGDtrwG3GOenb/manage/links) 
Gets a list of ancestors for Issues and Volumes
> [F] Reduce entity ambiguity

- packages/admin/__generated__/CollectionContributionListFragment.graphql.ts
- packages/admin/__generated__/collectionsSlugContributorsPagesQuery.graphql.ts
- packages/admin/__generated__/contributionsManageSlugCollectionsPagesQuery.graphql.ts
- packages/admin/components/composed/contribution/CollectionContributionList/CollectionContributionList.tsx
- Resolves WDP-660
ContributorNameColumnFragment was missing from parent fragment, which throws an error in dev and causes an infinite loop in build.
> [B] Fix contribution infinite loop in collections

- packages/admin/components/composed/collection/CollectionList/CollectionList.tsx
- packages/admin/components/composed/file/FileCreateModal/FileCreateModal.tsx
- packages/admin/components/composed/item/ItemList/ItemList.tsx
- packages/lib/api/components/QueryWrapper.tsx
The answer to why opening drawers in admin reloaded the underlying content turned out to be a bug in the refetch logic in `QueryWrapper`:
```
useEffect(() => {
if (!intersection(refetchTags, triggeredRefetchTags)) return;
retry();
}, [triggeredRefetchTags, refetchTags, retry]);
```
`!intersection(refetchTags, triggeredRefetchTags)` returns an empty array if there are no matches, so this condition was always true.
Also resolves:
- WDP-800
> [B] Fix retry condition in QueryWrapper

- packages/admin/components/layout/Drawer/Drawer.styles.ts
- packages/admin/components/layout/Drawer/Drawer.tsx
- packages/admin/components/layout/Modal/hooks/usePreventBodyScroll.ts
@jen-castiron I think this works, but it could definitely use another set of 👀 before merging. As I mentioned in Linear, even if this works, I think we could further improve performance of lists with lots of dialog components. It seems like body styles get set too many times by the various dialogs.
> [B] Fix body scroll lock for drawers

- packages/admin/__generated__/AppContextProviderQuery.graphql.ts
- packages/admin/__generated__/CollectionAddDrawerQuery.graphql.ts
- packages/admin/__generated__/CollectionAddDrawerRootQuery.graphql.ts
- packages/admin/__generated__/GlobalContextFragment.graphql.ts
- packages/admin/__generated__/ItemAddDrawerQuery.graphql.ts
- packages/admin/__generated__/SchemaSelectFragment.graphql.ts
- packages/admin/__generated__/SchemaSelectorModalOptionsFragment.graphql.ts
- packages/admin/components/api/MutationForm/MutationForm.tsx
- packages/admin/components/api/MutationForm/useMutationFormState.ts
- packages/admin/components/api/SchemaFormFields/SchemaFormFields.tsx
- packages/admin/components/composed/collection/CollectionAddForm/CollectionAddForm.tsx
- packages/admin/components/forms/SchemaSelect/SchemaSelect.tsx
- packages/admin/components/forms/SchemaSelector/SchemaSelector.tsx
- packages/admin/components/forms/SchemaSelector/SchemaSelectorModal.tsx
This PR updates MutationForm to filter out errors that are not paired with a field. When errors are added to react-hook-form, they're cleared _if_ they can be matched with a input field. If there's no matching input field, then the form will remain in an error state indefinitely. 
This PR also adds `user` errors to the global errors displayed on a form. Some of these errors display important information on why a form didn't save, but they're not included in either global or attribute error lists.
> [F] Fix bug with parent selector breaking on schema error

- packages/admin/components/composed/collection/CollectionLayout/CollectionLayout.tsx
When a record _has_ been harvested but no longer has associated harvest records, it won't be able to link back to its latest harvest record.
This was causing an infinite render loop when trying to render collections in just such a state.
> [B] Catch infinite loop with former harvested records
