NGLPteam/wdp-client

.storybook/preview.tsx
components/atomic/buttons/Button/Button.styles.ts
components/atomic/buttons/ButtonControl/ButtonControl.styles.ts
components/layout/Table/Table.styles.ts
theme/mixins/appearance.ts
theme/utility/appearance.ts

- Sets button background color to background-light, based on background class or mixin applied
- Resolves WDP-130

[F] Darken item button background color

---

components/atomic/MessageBlock/MessageBlock.styles.ts
components/atomic/forms/Search/Search.styles.ts
components/global/AppBody/index.tsx
components/global/Footer/Footer.styles.ts
components/global/Footer/Footer.tsx
components/global/Header/Header.styles.ts
components/global/MobileMenu/MobileMenu.styles.ts
components/global/MobileMenu/MobileMenu.tsx
components/layout/Drawer/Drawer.styles.ts
components/layout/Grid/Grid.styles.ts
components/layout/PageActions/PageActions.styled.ts
components/layout/PageHeader/PageHeader.styles.ts
components/layout/Table/Table.styles.ts
helpers/renderNavLink.tsx
theme/checkFlexGap.ts
theme/mixins/base.ts
theme/utility/layout.ts

[B] Fix Safari styling bugs

---

components/atomic/DataViewToggle/DataViewToggle.styles.ts
components/atomic/DataViewToggle/DataViewToggle.tsx
components/atomic/buttons/Button/Button.styles.ts
components/atomic/buttons/ButtonControl/ButtonControl.stories.tsx
components/atomic/buttons/ButtonControl/ButtonControl.styles.ts
components/atomic/buttons/ButtonControl/ButtonControl.tsx
components/atomic/buttons/ButtonControlGroup/ButtonControlGroup.stories.tsx
components/atomic/buttons/ButtonControlGroup/ButtonControlGroup.styles.ts
components/atomic/buttons/ButtonControlGroup/ButtonControlGroup.tsx
components/atomic/buttons/ButtonControlGroup/index.ts
components/atomic/buttons/index.ts
components/atomic/dropdown/Dropdown/Dropdown.stories.tsx
components/atomic/dropdown/Dropdown/Dropdown.styles.ts
components/atomic/dropdown/Dropdown/Dropdown.tsx
components/atomic/dropdown/DropdownMenu/DropdownMenu.styles.ts
components/composed/model/ModelList/hooks/useRowActions.tsx
components/global/Header/Header.styles.ts
components/global/Header/HeaderNavLinks.tsx
components/layout/Grid/Grid.stories.tsx
components/layout/PageHeader/PageHeader.styles.ts
helpers/localeStrings/en/common.json
hooks/useIsOutOfViewport.ts
theme/base/root.ts
theme/base/variables.ts
theme/mixins/appearance.ts
theme/utility/layout.ts

- A collapsible button group for item actions, etc
- ButtonControls can now handle authorization
- Resolves WDP-129

[F] Add ButtonControlGroup 

---

__generated__/ModelPageCountActionsFragment.graphql.ts
__generated__/collectionsCollectionChildQuery.graphql.ts
__generated__/collectionsCommunityChildQuery.graphql.ts
__generated__/collectionsQuery.graphql.ts
__generated__/communitiesQuery.graphql.ts
__generated__/contributorsQuery.graphql.ts
__generated__/itemsCollectionChildQuery.graphql.ts
__generated__/itemsItemChildQuery.graphql.ts
__generated__/itemsQuery.graphql.ts
__generated__/usersQuery.graphql.ts
components/atomic/forms/Typeahead/Typeahead.stories.tsx
components/composed/model/ModelPageCountActions/ModelPageCountActions.tsx

[B] Fix showing x - n, add perPage to page count fragment

---

components/atomic/Image/Image.tsx

[C] Don't optimize next/image locally

---

__generated__/ContributorListFragment.graphql.ts
__generated__/contributorsQuery.graphql.ts
components/composed/contributor/ContributorList/ContributorList.tsx
components/composed/model/ModelList/helpers/toEntities.ts

[C] Connect contributor delete button to API

---

__generated__/ContributorLayoutFragment.graphql.ts
__generated__/ContributorListFragment.graphql.ts
__generated__/ContributorUpdateDrawerQuery.graphql.ts
__generated__/collectionsSlugContributorsPagesQuery.graphql.ts
__generated__/contributorsQuery.graphql.ts
__generated__/itemsSlugContributorsPagesQuery.graphql.ts
components/composed/contributor/ContributorCreateOrganizationDrawer/ContributorCreateOrganizationDrawer.tsx
components/composed/contributor/ContributorCreateOrganizationForm/ContributorCreateOrganizationForm.tsx
components/composed/contributor/ContributorCreatePersonDrawer/ContributorCreatePersonDrawer.tsx
components/composed/contributor/ContributorCreatePersonForm/ContributorCreatePersonForm.tsx
components/composed/contributor/ContributorDisplayName/ContributorDisplayName.tsx
components/composed/contributor/ContributorLayout/ContributorLayout.tsx
components/composed/contributor/ContributorList/ContributorList.tsx
components/composed/contributor/ContributorUpdateDrawer/ContributorUpdateDrawer.tsx
components/composed/contributor/ContributorUpdateDrawer/index.tsx
components/composed/contributor/ContributorUpdateForm/ContributorUpdateForm.tsx
components/composed/contributor/ContributorUpdateOrganizationForm/ContributorUpdateOrganizationForm.tsx
components/composed/contributor/ContributorUpdatePersonForm/ContributorUpdatePersonForm.tsx
hooks/useDrawerHelper.ts
locales/en.json

[F] Build contributor edit drawer, improve create UX

---

__generated__/ItemListFragment.graphql.ts
__generated__/itemsQuery.graphql.ts
__generated__/itemsSlugCollectionsPagesQuery.graphql.ts
__generated__/itemsSlugItemsPagesQuery.graphql.ts
components/composed/item/ItemList/ItemList.tsx

[F] Connect item delete button to API

---

__generated__/contributionsManageSlugItemsQuery.graphql.ts
__generated__/detailsManageSlugItemsQuery.graphql.ts
__generated__/filesManageSlugItemsQuery.graphql.ts
__generated__/linksManageSlugItemsQuery.graphql.ts
__generated__/ordersManageSlugItemsQuery.graphql.ts
__generated__/pagesManageSlugItemsQuery.graphql.ts
__generated__/rulesManageSlugItemsQuery.graphql.ts
components/atomic/SidebarNav/SidebarNav.stories.tsx
components/atomic/SidebarNav/SidebarNav.tsx
components/composed/collection/CollectionLayout/CollectionLayout.tsx
components/composed/community/CommunityLayout/CommunityLayout.tsx
components/composed/contributor/ContributorLayout/ContributorLayout.tsx
components/composed/item/ItemLayout/ItemLayout.tsx
components/composed/user/UserLayout/UserLayout.tsx
components/layout/ContentSidebar/ContentSidebar.stories.tsx
components/layout/PageHeader/PageHeader.tsx
hooks/index.ts
hooks/useChildRouteLinks.ts
pages/items/[slug]/manage/contributions.tsx
pages/items/[slug]/manage/details.tsx
pages/items/[slug]/manage/files.tsx
pages/items/[slug]/manage/index.tsx
pages/items/[slug]/manage/links.tsx
pages/items/[slug]/manage/order.tsx
pages/items/[slug]/manage/pages.tsx
pages/items/[slug]/manage/rules.tsx
routes/baseRoutes.ts

In addition, this commit updates the props interface to tabNav and
sidebarNav so that they take a consistent link prop, which allows us to
simplify the layouts.

[F] Scaffold item manage pages

---

components/composed/user/UserList/UserList.tsx

For now, users may not be deleted from WDP.

[B] Remove user delete button

---

components/atomic/MessageBlock/index.ts
pages/index.tsx

[C] Improve home page placeholder content

---

__generated__/CollectionContributionEditDrawerQuery.graphql.ts
__generated__/CollectionContributionListFragment.graphql.ts
__generated__/ContributionUpdateFormFragment.graphql.ts
__generated__/ItemContributionEditDrawerQuery.graphql.ts
__generated__/ItemContributionListFragment.graphql.ts
__generated__/collectionsSlugContributorsPagesQuery.graphql.ts
__generated__/contributionsManageSlugCollectionsPagesQuery.graphql.ts
__generated__/contributionsManageSlugItemsQuery.graphql.ts
__generated__/itemsSlugContributorsPagesQuery.graphql.ts
components/composed/contribution/CollectionContributionEditDrawer/CollectionContributionEditDrawer.tsx
components/composed/contribution/CollectionContributionList/CollectionContributionList.tsx
components/composed/contribution/ContributionUpdateForm/ContributionUpdateForm.tsx
components/composed/contribution/ItemContributionEditDrawer/ItemContributionEditDrawer.tsx
components/composed/contribution/ItemContributionList/ItemContributionList.tsx
components/forms/inputType.d.ts
locales/en.json
pages/collections/[slug]/manage/contributions.tsx
pages/items/[slug]/manage/contributions.tsx

Additionally, render contributor and contribution object names in forms.

[F] Add contribution lists to items, collections

---

components/composed/contributor/ContributorUpdatePersonForm/ContributorUpdatePersonForm.tsx
components/forms/BaseInputWrapper/BaseInputWrapper.tsx
components/forms/Errors/Errors.tsx
components/forms/Errors/Message.tsx
components/forms/Errors/MessageList.tsx
components/forms/FileUpload/FileUpload.tsx
components/forms/Input/Input.tsx
components/forms/Select/Select.tsx
components/forms/Switch/Switch.tsx
components/forms/Textarea/Textarea.tsx
components/forms/Typeahead/Typeahead.tsx
components/forms/inputType.d.ts
theme/utility/appearance.ts

[B] Add labels to error messages and required fields

---

components/atomic/navs/MobileSubNav/MobileSubNav.tsx
components/atomic/navs/SidebarNav/SidebarNav.tsx
components/atomic/navs/TabNav/TabNav.tsx
components/global/Header/HeaderNavLinks.tsx
helpers/renderNavLink.tsx
routes/NextNamedRoutes.ts
routes/baseRoutes.ts

- Resolves WDP-228
Adds new functions to RouteHelper 
* isRouteNameActive and isRouteActive. Checks if the route is an exact match to the active route
* isRouteNameFuzzyActive and isRouteFuzzyActive. Checks  if the route or any of it's child routes are active

[F] Improve active state in primary navigation

---

.eslintrc.js
components/atomic/DataViewToggle/DataViewToggle.stories.tsx
components/atomic/DataViewToggle/DataViewToggle.tsx
components/atomic/DataViewToggle/index.ts
components/composed/collection/CollectionList/CollectionList.tsx
components/composed/community/CommunityList/CommunityList.tsx
components/composed/contribution/CollectionContributionList/CollectionContributionList.tsx
components/composed/contribution/ItemContributionList/ItemContributionList.tsx
components/composed/contributor/ContributorList/ContributorList.tsx
components/composed/item/ItemList/ItemList.tsx
components/composed/model/ModelGrid/ModelGridItem.tsx
components/composed/model/ModelList/ModelList.tsx
components/composed/model/ModelListActions/ModelListActions.tsx
components/composed/model/ModelListPage/ModelListPage.tsx
components/composed/user/UserList/UserList.tsx
hooks/index.ts
hooks/useLocalStorage.ts
hooks/useViewPreference.ts
utils/view-options.ts

Leaving this open until tomorrow morning so folks have time to look at it if they'd like.
- Create shared ViewOptions enum
- Update all components to use ViewOptions enum
- Create useLocalStorage and useViewPreference hooks
- Set default list view (table) and default list view options (table only)
- Resolves WDP-132
Thank you @scryptmouse for the useLocalStorage gist!

[F] Set list view value in local storage

---

components/composed/model/ModelListPage/ModelListPage.tsx

[B] List view should always be grid view on mobile

---

components/auth/SignInOut/SignInOut.styles.ts
components/auth/SignInOut/SignInOut.tsx
components/auth/SignInOut/index.ts
components/global/Header/Header.styles.ts
components/global/Header/Header.tsx
components/global/Header/HeaderAccount.tsx
fixtures/app.data.ts
hooks/useIsAuthenticated.ts
locales/en.json

@jen-castiron I've started building the avatar dropdown, but I wanted to get your eye on it before I do more.
Things I know need to be done:
- (Likely) replace my use of `useIsAuthenticated` with `useViewerContext` to grab both the avatar image and the signin state
- Add the dropdown items to `appData` rather than the mock I'm currently using and the labels to locales
- Related, create/add the routes for "Edit Profile" and "Edit Settings"
Let me know what you think the next steps are here.

[F] Add user avatar and dropdown menu

---

components/atomic/Pagination/Pagination.styles.ts
components/composed/model/ModelPagination/ModelPagination.tsx
components/layout/Grid/Grid.styles.ts
components/layout/Table/Table.styles.ts

Adds a condition for hiding pagination if the total page count is 1. Also, moves the bottom Table and Grid borders into Pagination so they are hidden if the controls are hidden.

[F] Hide pagination controls for single pages

---

__generated__/EntityLinksListFragment.graphql.ts
__generated__/ModelPageCountActionsFragment.graphql.ts
__generated__/collectionsManageSlugCollectionsPagesQuery.graphql.ts
__generated__/collectionsQuery.graphql.ts
__generated__/collectionsSlugCommunitiesPagesQuery.graphql.ts
__generated__/collectionsSlugContributorsPagesQuery.graphql.ts
__generated__/communitiesQuery.graphql.ts
__generated__/contributionsManageSlugCollectionsPagesQuery.graphql.ts
__generated__/contributionsManageSlugItemsQuery.graphql.ts
__generated__/contributorsQuery.graphql.ts
__generated__/itemsQuery.graphql.ts
__generated__/itemsSlugCollectionsPagesQuery.graphql.ts
__generated__/itemsSlugContributorsPagesQuery.graphql.ts
__generated__/itemsSlugItemsPagesQuery.graphql.ts
__generated__/linksManageSlugCollectionsPagesQuery.graphql.ts
__generated__/linksManageSlugItemsQuery.graphql.ts
__generated__/usersQuery.graphql.ts
components/composed/links/EntityLinksList/EntityLinksList.tsx
components/composed/links/EntityLinksList/index.tsx
components/composed/model/ModelColumns/BooleanColumn.tsx
components/composed/model/ModelColumns/StringColumn.tsx
components/composed/model/ModelPageCountActions/ModelPageCountActions.tsx
helpers/models.ts
locales/en.json
pages/collections/[slug]/manage/links.tsx
pages/items/[slug]/manage/links.tsx

- Comments out totalUnfilteredCount from pagination
- Fixes returned value in StringColumn and BooleanColumn
- Adds link lists to collections and items

[F] Add collection and item links list

---

.storybook/main.js
package-lock.json
package.json

🤞 resolves styling issues in Storybook

[B] Remove pseudo states addon for storybook

---

components/api/SchemaInstanceForm/Properties/ContributorsProperty/ContributorsProperty.tsx
components/api/SchemaInstanceForm/Properties/ScalarProperty/ScalarProperty.tsx
components/forms/Multiselect/HiddenMultiselect.tsx
components/forms/Multiselect/Multiselect.stories.tsx
components/forms/Multiselect/Multiselect.styles.ts
components/forms/Multiselect/Multiselect.tsx

storybook: https://wdp-storybook-git-jw-multiselect-cast-iron.vercel.app/?path=/story/components-forms-multiselect--in-a-form&globals=locale:en
Item: https://wdp-admin-client-git-jw-multiselect-cast-iron.vercel.app/items/pbneQbyFqLRncRo7Ipw59u0xXBQbOOk/manage/schema

[F] Use new Multiselect component in ContributorsProperty

---

components/api/SchemaInstanceForm/Properties/TagsProperty/TagsProperty.tsx
components/forms/BaseArrayList/BaseArrayList.styles.ts
components/forms/BaseArrayList/BaseArrayList.tsx
components/forms/BaseArrayList/BaseArrayListItem.tsx
components/forms/BaseArrayList/index.ts
components/forms/Multiselect/Multiselect.styles.ts
components/forms/Multiselect/Multiselect.tsx
components/forms/TagsInput/TagsInput.stories.tsx
components/forms/TagsInput/TagsInput.styles.ts
components/forms/TagsInput/TagsInput.tsx
components/forms/TagsInput/TagsInputAdd.tsx
components/forms/TagsInput/index.ts
locales/en.json

- Add tag input to schema property factory
TODO:

[F] Create Tag Input

---

components/layout/Drawer/Drawer.tsx

Adds a loading state to drawers

[F] Add LoadingCircle to edit drawers

---

__generated__/ContributorListFragment.graphql.ts
__generated__/contributorsQuery.graphql.ts
components/atomic/buttons/ButtonControl/ButtonControl.styles.ts
components/atomic/buttons/ButtonControl/patterns/ButtonControlConfirm.tsx
components/atomic/buttons/ButtonControlGroup/ButtonControlGroup.tsx
components/atomic/dropdown/Dropdown/Dropdown.styles.ts
components/composed/contributor/ContributorList/ContributorList.tsx
components/composed/model/ModelGrid/ModelGrid.tsx
components/composed/model/ModelList/ModelList.tsx
components/composed/model/ModelListActions/ModelListActions.tsx
components/composed/model/ModelListPage/ModelListPage.tsx
components/composed/model/ModelTable/ModelTable.tsx
components/layout/Grid/Grid.tsx
components/layout/Table/Table.tsx
components/layout/Table/TableSortIcon.tsx
locales/en.json
pages/_document.tsx

- Add missing alt text in thumbnail images
- Add missing delete button text
- Add missing lang attribute

[B] Fix a11y issues

---

components/api/SchemaInstanceForm/SchemaInstanceForm.tsx
components/forms/SchemaSelector/SchemaSelector.styles.ts

- Move SchemaSelector out of SchemaInstanceProvider

[B] Fix confusing messaging on schema change

---

__generated__/SlugCollectionsPageQuery.graphql.ts
components/atomic/loading/LoadingCircle/LoadingCircle.styles.ts
components/layout/PageHeader/PageHeader.styles.ts
package.json
pages/collections/[slug]/index.tsx
routes/baseRoutes.ts

Query for a collection's children before redirecting to child collections. If no child collections are found, redirect to child items.
- Resolves WDP-289

[F] Redirect to items if collection does not have child collections

---

package-lock.json
packages/admin/__generated__/EntityOrderingListDataFragment.graphql.ts
packages/admin/__generated__/orderManageSlugOrderingsPagesQuery.graphql.ts
packages/admin/__generated__/ordersManageSlugItemsQuery.graphql.ts
packages/admin/components/composed/ordering/EntityOrderingList/EntityOrderingList.tsx
packages/admin/locales/en.json

Adds `inheritedFromSchema` and `createdAt` columns to ordering list pages.

[F] Add columns to ordering lists

---

packages/admin/components/atomic/Toast/Toast.stories.tsx
packages/admin/components/atomic/Toast/Toast.tsx
packages/admin/components/atomic/loading/LoadingCircle/LoadingCircle.styles.ts
packages/admin/components/composed/collection/CollectionList/CollectionList.tsx
packages/admin/components/forms/BaseSelect/BaseSelect.styles.ts
packages/admin/components/forms/Select/Select.stories.tsx
packages/admin/components/global/Header/Header.tsx
packages/admin/theme/base/resets.ts

Fixed: text alignment
To Do: background color on select

[B] Improve styling of selects in Firefox

---

packages/admin/components/atomic/Pagination/PaginationWrapper.tsx
packages/admin/theme/utility/appearance.ts

Adds a new appearance class for pagination input styles.

[B] Fix pagination styling in Firefox

---

packages/admin/components/composed/ordering/EntityOrderingAddDrawer/EntityOrderingAddDrawer.tsx
packages/admin/components/composed/ordering/EntityOrderingAddForm/EntityOrderingAddForm.tsx
packages/admin/components/composed/ordering/EntityOrderingList/EntityOrderingList.tsx
packages/admin/components/forms/Fieldset/Fieldset.styles.ts
packages/admin/components/forms/Fieldset/Fieldset.tsx
packages/admin/components/forms/RadioGroup/RadioGroup.tsx
packages/admin/components/forms/Select/Select.tsx
packages/admin/locales/en.json
packages/admin/theme/base/root.ts

First working version of the Add Dynamic Ordering form!
Two known issues:
- `identifier` is not guaranteed to be unique. Need to add a uid.
- `OrderingSelectDefintionInput` only takes the value selected for Collections.

[F] Build Add Dynamic Ordering form

---

packages/admin/components/composed/model/ModelGrid/ModelGrid.tsx
packages/admin/components/composed/model/ModelPageCountActions/ModelPageCountActions.tsx
packages/admin/components/layout/BackToAll/BackToAll.tsx
packages/admin/components/layout/ContentHeader/ContentHeader.tsx
packages/admin/components/layout/Grid/Grid.stories.tsx
packages/admin/components/layout/Grid/Grid.styles.ts
packages/admin/components/layout/Grid/Grid.tsx
packages/admin/components/layout/PageCountActions/PageCountActions.stories.tsx
packages/admin/components/layout/PageCountActions/PageCountActions.tsx
packages/admin/components/layout/Table/Table.stories.tsx
packages/admin/locales/en.json
packages/admin/pages/_app.tsx
packages/admin/pages/collections/[slug]/manage/details.tsx
packages/admin/pages/communities/[slug]/manage/details.tsx
packages/admin/pages/contributors/[slug]/details.tsx
packages/admin/pages/items/[slug]/manage/details.tsx
packages/admin/pages/users/[slug]/details.tsx

Adds loading state to:
- Grids
- Page count
- Content Title (I'm not thrilled with this, could be better)
- Detail pages

[F] Add missing loading states

---

packages/frontend/theme/mixins/appearance.ts
packages/frontend/theme/utility/appearance.ts

Adds styles for `.a-button-primary--sm` and `.a-button-secondary--sm` utility classes.

[F] Add sm button classes

---

packages/admin/components/api/SchemaInstanceForm/Factories/GroupProperty/GroupProperty.tsx
packages/admin/components/composed/model/ModelColumns/ContributorsColumn.tsx
packages/admin/components/forms/Fieldset/Fieldset.styles.ts
packages/admin/components/forms/FieldsetSection/FieldsetSection.stories.tsx
packages/admin/components/forms/FieldsetSection/FieldsetSection.styles.ts
packages/admin/components/forms/FieldsetSection/FieldsetSection.tsx
packages/admin/components/forms/FieldsetSection/index.ts
packages/admin/components/forms/index.ts
packages/admin/theme/base/root.ts

[B] Fix extra space in contributors column
[F] Add FieldsetSection and restyle Fieldsets

[F] Add FieldsetSection and restyle Fieldsets

---

packages/frontend/components/atomic/Button/Button.styles.ts
packages/frontend/components/composed/article/ArticleLayout/ArticleLayout.tsx
packages/frontend/components/composed/issue/IssueContent/IssueContent.styles.ts
packages/frontend/components/composed/issue/IssueContent/IssueContent.tsx
packages/frontend/components/global/AppBody/AppBody.styles.ts
packages/frontend/components/layout/BackToTopBlock/BackToTopBlock.stories.tsx
packages/frontend/components/layout/BackToTopBlock/BackToTopBlock.styles.ts
packages/frontend/components/layout/BackToTopBlock/BackToTopBlock.tsx
packages/frontend/components/layout/BackToTopBlock/index.ts
packages/frontend/components/layout/index.ts
packages/frontend/locales/en.json

- a wrapper div with a back to top button
- Resolves WDP-436 and WDP-412

[F] Build BackToTopBlock

---

packages/admin/__generated__/CollectionUpdateDrawerQuery.graphql.ts
packages/admin/__generated__/ItemUpdateDrawerQuery.graphql.ts
packages/admin/__generated__/SchemaPropertyFragment.graphql.ts
packages/admin/__generated__/URLPropertyFragment.graphql.ts
packages/admin/__generated__/detailsManageSlugCollectionsPagesQuery.graphql.ts
packages/admin/__generated__/detailsManageSlugItemsQuery.graphql.ts
packages/admin/components/api/SchemaInstanceForm/Factories/SchemaProperty/SchemaProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/AssetProperty/AssetProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/AssetsProperty/AssetsProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/BooleanProperty/BooleanProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/ContributorProperty/ContributorProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/ContributorsProperty/ContributorsProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/DateProperty/DateProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/EmailProperty/EmailProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/FloatProperty/FloatProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/FullTextProperty/FullTextProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/IntegerProperty/IntegerProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/MarkdownProperty/MarkdownProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/MultiselectProperty/MultiselectProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/ScalarProperty/ScalarProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/SelectProperty/SelectProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/StringProperty/StringProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/TagsProperty/TagsProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/URLProperty/URLProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/URLProperty/index.ts
packages/admin/components/api/SchemaInstanceForm/Properties/VariableDateProperty/VariableDateProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/index.ts

- [C] Remove register from ScalarProperty

F] Add URLProperty to admin

---

packages/frontend/__generated__/ContributorSlugItemQuery.graphql.ts
packages/frontend/__generated__/FileSlugItemQuery.graphql.ts
packages/frontend/__generated__/IssueLayoutFragment.graphql.ts
packages/frontend/__generated__/PageSlugCollectionQuery.graphql.ts
packages/frontend/__generated__/PageSlugItemQuery.graphql.ts
packages/frontend/__generated__/PrevNextIssueFragment.graphql.ts
packages/frontend/__generated__/SlugCollectionQuery.graphql.ts
packages/frontend/__generated__/SlugItemQuery.graphql.ts
packages/frontend/__generated__/contributorsSlugItemQuery.graphql.ts
packages/frontend/__generated__/filesSlugItemQuery.graphql.ts
packages/frontend/__generated__/metricsSlugItemQuery.graphql.ts
packages/frontend/components/atomic/Button/patterns/PrevNextButton/PrevNextButton.styles.ts
packages/frontend/components/atomic/Button/patterns/PrevNextButton/PrevNextButton.tsx
packages/frontend/components/atomic/Button/patterns/PrevNextButton/index.ts
packages/frontend/components/atomic/Button/patterns/index.ts
packages/frontend/components/composed/issue/IssueLayout/IssueLayout.tsx
packages/frontend/components/composed/issue/PrevNextIssue/PrevNextIssue.styles.ts
packages/frontend/components/composed/issue/PrevNextIssue/PrevNextIssue.tsx
packages/frontend/components/composed/issue/PrevNextIssue/index.ts
packages/frontend/locales/en.json

Builds design for Prev-Next Issue block. Query needs to be updated and links added when the API is ready. Also, adds new Button pattern for PrevNextButton.

[F] Build Prev-Next Issue block

---

packages/admin/components/forms/Search/Search.styles.ts
packages/frontend/components/forms/Search/Search.styles.ts

[B] Truncate search placeholder text

---

packages/frontend/components/atomic/Accordion/Accordion.stories.tsx
packages/frontend/components/atomic/Accordion/Accordion.styles.tsx
packages/frontend/components/atomic/Accordion/Accordion.tsx
packages/frontend/components/atomic/Accordion/index.ts
packages/frontend/components/atomic/index.ts
packages/frontend/components/composed/community/CommunityNavList/CommunityNavList.tsx

@jen-castiron Here's a first pass on the Accordion component. Right now the styles are tightly coupled to the component. I think it would be easy to split this out into an unstyled `BaseAccordion` and `Accordion` like we have for Dropdown, but I thought it might be better to wait on that until we implement it in  more than one place and see what we need.

[F] Build mobile accordion component

---

packages/admin/__generated__/CollectionUpdateDrawerQuery.graphql.ts
packages/admin/__generated__/CollectionUpdateFormFieldsFragment.graphql.ts
packages/admin/__generated__/CollectionUpdateFormMutation.graphql.ts
packages/admin/__generated__/ItemUpdateDrawerQuery.graphql.ts
packages/admin/__generated__/ItemUpdateFormFieldsFragment.graphql.ts
packages/admin/__generated__/ItemUpdateFormMutation.graphql.ts
packages/admin/__generated__/VariableDatePropertyFragment.graphql.ts
packages/admin/__generated__/VariablePrecisionDateControlFragment.graphql.ts
packages/admin/__generated__/detailsManageSlugCollectionsPagesQuery.graphql.ts
packages/admin/__generated__/detailsManageSlugItemsQuery.graphql.ts
packages/admin/__schema__/schema.json
packages/admin/components/api/SchemaInstanceForm/Properties/VariableDateProperty/VariableDateProperty.tsx
packages/admin/components/composed/collection/CollectionAddForm/CollectionAddForm.tsx
packages/admin/components/composed/collection/CollectionUpdateForm/CollectionUpdateForm.tsx
packages/admin/components/composed/item/ItemAddForm/ItemAddForm.tsx
packages/admin/components/composed/item/ItemUpdateForm/ItemUpdateForm.tsx
packages/admin/components/forms/VariableDatePicker/VariableDatePicker.stories.tsx
packages/admin/components/forms/VariableDatePicker/VariableDatePicker.tsx
packages/admin/components/forms/VariablePrecisionDateControl/VariablePrecisionDateControl.tsx
packages/admin/components/forms/VariablePrecisionDateControl/index.ts
packages/admin/components/forms/index.ts
packages/admin/locales/en.json
packages/admin/schema.graphql
packages/admin/types/graphql-schema.d.ts
packages/frontend/__schema__/schema.json
packages/frontend/schema.graphql
packages/frontend/types/graphql-schema.d.ts

[F] Add published, issued, available and accessioned to forms (Resolves WDP-505 and WDP-508)
[B] Remove required subtitle field from update collection (Resolves WDP-489)

[F] Add published, issued, available and accessioned to forms 

---

packages/frontend/components/composed/collections/FeaturedCollectionsGrid/FeaturedCollectionsGrid.styles.tsx

[B] Fix aspect ratio on Featured Collections Grid

---

packages/frontend/components/composed/article/ArticleContributor/ArticleContributor.styles.ts
packages/frontend/components/composed/article/ArticleContributor/ArticleContributor.tsx
packages/frontend/components/composed/contributor/ContributorDetail/ContributorDetail.tsx

- limit author bio to three lines
- remove headers

[B] Article author block bio text

---

packages/frontend/__generated__/InstanceCommunitiesFragment.graphql.ts
packages/frontend/__generated__/InstanceCommunitySummaryFragment.graphql.ts
packages/frontend/__generated__/InstanceContentLayoutFragment.graphql.ts
packages/frontend/__generated__/pagesQuery.graphql.ts
packages/frontend/components/composed/instance/InstallationName/InstallationName.tsx
packages/frontend/components/composed/instance/InstanceCommunities/InstanceCommunities.styles.ts
packages/frontend/components/composed/instance/InstanceCommunities/InstanceCommunities.tsx
packages/frontend/components/composed/instance/InstanceCommunities/index.ts
packages/frontend/components/composed/instance/InstanceCommunitySummary/InstanceCommunitySummary.styles.ts
packages/frontend/components/composed/instance/InstanceCommunitySummary/InstanceCommunitySummary.tsx
packages/frontend/components/composed/instance/InstanceCommunitySummary/index.ts
packages/frontend/components/composed/instance/InstanceContentLayout/InstanceContentLayout.tsx
packages/frontend/components/composed/instance/InstanceContentLayout/index.ts
packages/frontend/components/composed/instance/InstanceHero/InstanceHero.styles.ts
packages/frontend/components/composed/instance/InstanceHero/InstanceHero.tsx
packages/frontend/components/composed/instance/InstanceHero/index.ts
packages/frontend/locales/en.json
packages/frontend/pages/index.tsx

[F] instance content layout

---

packages/frontend/components/composed/community/CommunityLayout/CommunityLayout.tsx
packages/frontend/components/global/AppBody/AppBody.tsx
packages/frontend/components/global/AppFooter/AppFooter.tsx
packages/frontend/theme/mixins/appearance.ts

Also fixes accessibility issue - sets "lighter" color to neutral80 on custom20 backgrounds

[B] Set footer color to custom20

---

packages/frontend/__generated__/ArticleMetadataBlockFragment.graphql.ts
packages/frontend/__generated__/ContributionSummaryEntityFragment.graphql.ts
packages/frontend/__generated__/ContributionSummaryFragment.graphql.ts
packages/frontend/__generated__/ContributorDetailFragment.graphql.ts
packages/frontend/__generated__/SlugContributorCollectionPageQuery.graphql.ts
packages/frontend/__generated__/SlugContributorItemPageQuery.graphql.ts
packages/frontend/__generated__/SlugContributorPageQuery.graphql.ts
packages/frontend/__generated__/metadataSlugItemQuery.graphql.ts
packages/frontend/components/composed/contribution/ContributionSummary/ContributionSummary.styles.ts
packages/frontend/components/composed/contribution/ContributionSummary/ContributionSummary.tsx
packages/frontend/components/composed/contribution/ContributionSummary/index.ts
packages/frontend/components/composed/contributor/ContributorDetail/ContributorDetail.tsx
packages/frontend/components/composed/instance/InstallationName/InstallationName.tsx
packages/frontend/components/composed/journal/CurrentIssue/CurrentIssue.tsx
packages/frontend/components/composed/journal/FeaturedJournals/FeaturedJournal/FeaturedJournal.styles.ts
packages/frontend/components/composed/journal/FeaturedJournals/FeaturedJournal/FeaturedJournal.tsx
packages/frontend/components/composed/journal/FeaturedJournals/FeaturedJournal/index.ts
packages/frontend/components/composed/journal/FeaturedJournals/FeaturedJournals.styles.ts
packages/frontend/components/composed/unit/UnitList/UnitList.styles.tsx
packages/frontend/components/composed/unit/UnitList/UnitList.tsx
packages/frontend/components/composed/viewer/AccountDropdown/AccountDropdown.styles.ts
packages/frontend/components/composed/viewer/AccountDropdown/AccountDropdown.tsx
packages/frontend/components/factories/MetadataFactory/properties/URLProperty.tsx
packages/frontend/components/global/AppFooter/AppFooter.styles.ts
packages/frontend/components/global/AppFooter/AppFooter.tsx
packages/frontend/components/global/AppHeader/AppHeader.styles.ts
packages/frontend/components/global/AppHeader/AppHeader.tsx
packages/frontend/components/layout/BackToTopBlock/BackToTopBlock.styles.ts
packages/frontend/components/layout/BackToTopBlock/BackToTopBlock.tsx
packages/frontend/theme/mixins/typography.ts

- [B] Fix unit links
- [B] Fix current issue name hover
- [B] Fix back to top block width
- [B] Fix account dropdown padding
- [B] Fix featured journal hover color
- [B] Add contributor role to contributor detail articles

[B] Frontend clean up

---

packages/admin/components/api/SchemaInstanceForm/Properties/SelectProperty/SelectProperty.tsx
packages/admin/components/composed/community/CommunityCreateForm/CommunityCreateForm.tsx
packages/admin/components/composed/community/CommunityUpdateForm/CommunityUpdateForm.tsx
packages/admin/components/forms/BaseSelect/BaseSelect.tsx
packages/admin/locales/en.json

- Set hero layout default for Communities to ONE_COLUMN

[B] Update create community form to match update community form

---

packages/frontend/theme/mixins/typography.ts

- Only noticible when Sentient is selected as the app font theme

[B] Fix header fonts

---

packages/admin/components/forms/AssetsPropertyControl/AssetsPropertyControl.stories.tsx
packages/admin/components/forms/AssetsPropertyControl/AssetsPropertyControl.tsx
packages/admin/components/forms/Select/Select.stories.tsx
packages/admin/components/forms/TagsInput/TagsInputAdd.tsx
packages/lib/package.json
packages/lib/storybook/RelayEnvironmentProvider.tsx
packages/lib/storybook/RelayStorybook.tsx
packages/lib/storybook/index.ts
yarn.lock

- Adds RelayStorybook and RelayEnvironmentProvider to lib package

[C] Add AssetsPropertyControl to storybook

---

packages/admin/locales/en.json
packages/frontend/components/atomic/links/Link/Link.stories.tsx
packages/frontend/components/atomic/links/Link/Link.styles.ts
packages/frontend/components/atomic/links/Link/Link.tsx
packages/frontend/components/atomic/links/Link/patterns/LinkPatterns.stories.tsx
packages/frontend/components/atomic/links/Link/patterns/ORCIDLink.tsx
packages/frontend/components/atomic/links/index.ts
packages/frontend/components/composed/contributor/ContributorDetail/ContributorDetail.tsx
packages/frontend/components/factories/IconFactory/IconFactory.tsx
packages/frontend/components/svgs/icons/ORCID.tsx
packages/frontend/components/svgs/icons/index.ts

[F] Adjust ORCID rendering

---

packages/admin/.env
packages/admin/__generated__/DashboardCollectionsFragment.graphql.ts
packages/admin/__generated__/DashboardCollectionsListFragment.graphql.ts
packages/admin/__generated__/DashboardInstallationFragment.graphql.ts
packages/admin/__generated__/DashboardLayoutFragment.graphql.ts
packages/admin/__generated__/pagesHomeQuery.graphql.ts
packages/admin/components/composed/dashboard/DashboardCollections/DashboardCollections.tsx
packages/admin/components/composed/dashboard/DashboardCollections/index.ts
packages/admin/components/composed/dashboard/DashboardHomeMessage.tsx
packages/admin/components/composed/dashboard/DashboardInstallation/DashboardInstallation.styles.ts
packages/admin/components/composed/dashboard/DashboardInstallation/DashboardInstallation.tsx
packages/admin/components/composed/dashboard/DashboardInstallation/index.ts
packages/admin/components/composed/dashboard/DashboardLayout/DashboardLayout.styles.ts
packages/admin/components/composed/dashboard/DashboardLayout/DashboardLayout.tsx
packages/admin/components/composed/dashboard/DashboardLayout/index.ts
packages/admin/components/composed/dashboard/index.ts
packages/admin/components/composed/model/ModelList/ModelList.tsx
packages/admin/components/composed/model/ModelList/hooks/useModelList.tsx
packages/admin/fixtures/app.data.ts
packages/admin/locales/en.json
packages/admin/pages/index.tsx
packages/lib/helpers/index.ts
packages/lib/helpers/numbers.ts

Current list of collections is empty. Don't merge until API returns list of collections across communities.

[F] Add dashboard

---

packages/admin/__generated__/CollectionContributionCreateDrawerQuery.graphql.ts
packages/admin/__generated__/CollectionTypeaheadFragment.graphql.ts
packages/admin/__generated__/ContributorContributionCreateDrawerQuery.graphql.ts
packages/admin/__generated__/ItemContributionCreateDrawerQuery.graphql.ts
packages/admin/__generated__/NodeRoleSelectQuery.graphql.ts
packages/admin/__generated__/RoleEditAccessDrawerQuery.graphql.ts
packages/admin/__generated__/RoleGrantAccessDrawerQuery.graphql.ts
packages/admin/__generated__/RoleGrantAccessFormFragment.graphql.ts
packages/admin/__generated__/RoleGrantAccessFormRolesFragment.graphql.ts
packages/admin/__generated__/RoleSelectFragment.graphql.ts
packages/admin/__generated__/UserGrantCollectionAccessDrawerQuery.graphql.ts
packages/admin/__generated__/UserGrantCollectionAccessFormFragment.graphql.ts
packages/admin/__generated__/UserGrantCommunityAccessDrawerQuery.graphql.ts
packages/admin/__generated__/UserGrantCommunityAccessFormFragment.graphql.ts
packages/admin/__generated__/UserGrantItemAccessDrawerQuery.graphql.ts
packages/admin/__generated__/UserGrantItemAccessFormFragment.graphql.ts
packages/admin/__schema__/schema.json
packages/admin/components/composed/role/RoleEditAccessDrawer/RoleEditAccessDrawer.tsx
packages/admin/components/composed/role/RoleEditAccessForm/RoleEditAccessForm.tsx
packages/admin/components/composed/role/RoleGrantAccessDrawer/RoleGrantAccessDrawer.tsx
packages/admin/components/composed/role/RoleGrantAccessForm/RoleGrantAccessForm.tsx
packages/admin/components/composed/user/UserGrantCollectionAccessForm/UserGrantCollectionAccessForm.tsx
packages/admin/components/composed/user/UserGrantCommunityAccessForm/UserGrantCommunityAccessForm.tsx
packages/admin/components/composed/user/UserGrantItemAccessForm/UserGrantItemAccessForm.tsx
packages/admin/components/forms/CollectionTypeahead/CollectionTypeahead.tsx
packages/admin/components/forms/RoleSelect/RoleSelect.tsx
packages/admin/components/forms/RoleSelect/index.ts
packages/admin/components/forms/RoleSelect/patterns/NodeRoleSelect.tsx
packages/admin/schema.graphql
packages/admin/types/graphql-schema.d.ts

[C] Use entity's assignableRoles in add/edit role forms

---

packages/admin/__generated__/DashboardCollectionsFragment.graphql.ts
packages/admin/__generated__/DashboardCollectionsListFragment.graphql.ts
packages/admin/__generated__/pagesHomeQuery.graphql.ts
packages/admin/components/composed/dashboard/DashboardCollections/DashboardCollections.tsx
packages/admin/components/layout/Grid/Grid.styles.ts
packages/admin/components/layout/Grid/Grid.tsx
packages/admin/theme/mixins/base.ts
packages/admin/utils/view-options.ts
packages/lib/hooks/index.ts
packages/lib/hooks/useBoundingBox.ts
packages/lib/hooks/useWindowSize.ts

- Resolves WDP-632
- Resolves WDP-629
- Use mobile layout in dashboard collections list
- Limit results to 10

[F] Improve dashboard collections list

---

packages/frontend/components/composed/issue/IssueOrderingLayout/IssueOrderingLayout.tsx
packages/frontend/components/layout/BrowseListLayout/BrowseListLayout.tsx
packages/frontend/components/layout/NoContent/NoContent.stories.tsx
packages/frontend/components/layout/NoContent/NoContent.styles.ts
packages/frontend/components/layout/NoContent/NoContent.tsx
packages/frontend/components/layout/NoContent/index.tsx
packages/frontend/components/layout/index.ts
packages/frontend/locales/en.json

[F] Add no content block

---

packages/admin/.env
packages/admin/next.config.js
packages/frontend/.env
packages/frontend/next.config.js

Additionally update imageDomains to support testing against local API instance

[C] Update Keycloak URL

---

packages/frontend/components/composed/article/ArticleTabNav/ArticleTabNav.tsx
packages/frontend/components/composed/asset/AssetPDFPage/AssetPDFPage.styles.ts
packages/frontend/components/composed/asset/AssetsBlock/AssetBlockItem/AssetBlockItem.styles.ts
packages/frontend/components/composed/asset/AssetsBlock/AssetBlockItem/AssetBlockItem.tsx

[B] Fix asset file tab active state

---

packages/admin/components/forms/VariablePrecisionDateControl/VariablePrecisionDateControl.tsx

[B] Fix schema variable date props default value

---

packages/admin/components/composed/item/ItemLayout/ItemLayout.tsx
packages/admin/components/composed/role/RoleEditAccessDrawer/RoleEditAccessDrawer.tsx

[B] Admin UI Fixes

---

packages/admin/pages/_middleware.ts
packages/frontend/pages/_middleware.ts
packages/lib/app/middleware.ts

[C] Force HTTPS in production

---

packages/admin/__generated__/GlobalSettingsEditDrawerQuery.graphql.ts
packages/admin/__generated__/GlobalSettingsEditFormFragment.graphql.ts
packages/admin/__generated__/GlobalSettingsEditFormMutation.graphql.ts
packages/admin/__schema__/schema.json
packages/admin/components/composed/settings/GlobalSettingsEditForm/GlobalSettingsEditForm.tsx
packages/admin/locales/en.json
packages/admin/schema.graphql
packages/admin/types/graphql-schema.d.ts
packages/frontend/__generated__/InstanceHeroFragment.graphql.ts
packages/frontend/__generated__/pagesQuery.graphql.ts
packages/frontend/__schema__/schema.json
packages/frontend/components/composed/instance/InstanceHero/InstanceHero.tsx
packages/frontend/schema.graphql
packages/frontend/types/graphql-schema.d.ts

[F] Add instance copy field to admin and frontend

---

packages/frontend/components/composed/search/SearchOrderBy/SearchOrderBy.tsx

[F] Add sort by created date

---

packages/admin/components/forms/AssetPropertySelect/AssetPropertySelect.styles.ts

[B] Fix style issue with asset picker

---

packages/admin/components/atomic/buttons/ButtonControl/ButtonControl.styles.ts
packages/frontend/components/composed/community/CommunityName/CommunityLogo/CommunityLogo.tsx
packages/frontend/components/global/AppFooter/AppFooter.styles.ts

Also, resolves:
- WDP-794
- WDP-796

[B] Various style fixes

---

packages/admin/components/composed/file/FileEditForm/FileEditForm.tsx
packages/admin/components/composed/user/UserGrantCollectionAccessForm/UserGrantCollectionAccessForm.tsx
packages/admin/components/composed/user/UserGrantCommunityAccessForm/UserGrantCommunityAccessForm.tsx
packages/admin/components/composed/user/UserGrantItemAccessForm/UserGrantItemAccessForm.tsx
packages/admin/components/composed/user/UserLayoutQuery/UserLayoutQuery.tsx
packages/admin/hooks/useDestroyer.ts
packages/admin/pages/collections/[slug]/collections.tsx
packages/admin/pages/collections/[slug]/items.tsx
packages/admin/pages/communities/[slug]/collections.tsx
packages/admin/pages/contributors/[slug]/collections.tsx
packages/admin/pages/contributors/[slug]/items.tsx
packages/admin/pages/contributors/index.tsx
packages/admin/pages/items/[slug]/items.tsx
packages/admin/pages/users/[slug]/collections.tsx
packages/admin/pages/users/[slug]/communities.tsx
packages/admin/pages/users/[slug]/items.tsx

@jen-castiron I updated `useDestroyer` to trigger refetch tags. I also added a number of additional tags that seemed like they were still missing from lists. Would love your 👀 on those to make sure I got them right.

[F] Refresh list counts after deletions

---

packages/admin/components/composed/model/ModelTable/ModelTable.tsx

[B] Hide table headers on load

---

packages/frontend/components/composed/community/CommunityNavList/CommunityNavList.tsx

[B] Hide explore dropdown menu if menu is empty

---

packages/admin/__generated__/useResetOrderingFragment.graphql.ts
packages/admin/__generated__/useResetOrderingMutation.graphql.ts
packages/admin/components/composed/collection/CollectionLayoutQuery/CollectionLayoutQuery.tsx
packages/admin/components/composed/model/ModelList/hooks/useModelList.tsx
packages/admin/components/composed/model/ModelList/hooks/useRowActions.tsx
packages/admin/components/composed/ordering/EntityOrderingList/EntityOrderingList.tsx
packages/admin/hooks/useResetOrdering.ts
packages/admin/locales/en.json

The icons need some work, or we could try a different approach
TODO:

[F] Add new enable and disable buttons to rows

---

packages/admin/__generated__/EntityTypeaheadQuery.graphql.ts
packages/admin/components/composed/contribution/ContributionCreateForm/ContributionCreateForm.tsx
packages/admin/components/forms/BaseTypeahead/BaseTypeahead.styles.ts
packages/admin/components/forms/BaseTypeahead/BaseTypeahead.tsx
packages/admin/components/forms/EntitySelector/EntitySelector.styles.ts
packages/admin/components/forms/EntitySelector/EntitySelector.tsx
packages/admin/components/forms/EntitySelector/EntitySelectorController.tsx
packages/admin/components/forms/EntitySelector/EntitySelectorDisclosure/EntitySelectorDisclosure.styles.ts
packages/admin/components/forms/EntitySelector/EntitySelectorDisclosure/EntitySelectorDisclosure.tsx
packages/admin/components/forms/EntitySelector/EntitySelectorDisclosure/hooks/useDisclosureState.ts
packages/admin/components/forms/EntitySelector/EntitySelectorDisclosure/index.ts
packages/admin/components/forms/EntitySelector/EntitySelectorItem/EntitySelectorItem.tsx
packages/admin/components/forms/EntitySelector/EntityTypeahead/EntityTypeahead.tsx
packages/admin/components/forms/EntitySelector/EntityTypeahead/index.ts
packages/admin/components/forms/ParentSelector/ParentSelectorModal.tsx
packages/admin/package.json
packages/lib/api/components/QueryWrapper.tsx
yarn.lock

@jen-castiron I think the combo typehead + entity selector works! Let me know if you see performance or UX issues.
Can preview [here](https://wdp-admin-lrzkzz54f-cast-iron.vercel.app/contributors/J6GNobp5TD7yBUwZdt0DJ7C5zP7Q2azL/items?order=RECENT&drawer=addContributorContribution&drawerSlug=J6GNobp5TD7yBUwZdt0DJ7C5zP7Q2azL&drawerContributionType=item).

[POC][F] Build EntitySelectorDisclosure

---

packages/admin/__generated__/contributorsQuery.graphql.ts
packages/admin/components/composed/contributor/ContributorList/ContributorList.tsx
packages/admin/components/composed/model/ModelListPage/ModelListPage.tsx
packages/admin/hooks/index.ts
packages/admin/hooks/useContributorQueryVars.ts
packages/admin/pages/contributors/index.tsx

Adds `prefix` search to contributors list, but probably requires an api update for a full search. Search should probably also be added to the users list.

[WIP][F] Add search to contributors list

---

packages/admin/pages/_document.tsx

[F] Fix preloaded font file reference

---

packages/admin/components/composed/contributor/ContributorCreatePersonForm/ContributorCreatePersonForm.tsx
packages/admin/components/composed/contributor/ContributorUpdateOrganizationForm/ContributorUpdateOrganizationForm.tsx
packages/admin/components/composed/contributor/ContributorUpdatePersonForm/ContributorUpdatePersonForm.tsx
packages/admin/pages/collections/index.tsx
packages/admin/pages/communities/index.tsx
packages/admin/pages/contributors/index.tsx
packages/admin/pages/items/index.tsx

- Resolves MERU-855
@1aurend is there a refetch mechanism that should be working instead of refetch tags? Or is it OK to add these refetch tags back in?

[F] Add refetch tags to communities, collections, items, contributors list

---

packages/admin/components/api/MutationForm/MutationForm.tsx
packages/admin/components/forms/SchemaSelector/SchemaSelector.tsx

- Fixes MERU-857, submitting update schema modal form also submits update entity form

[B] Fix form submit event propogation

---

packages/admin/components/api/hooks/types.d.ts
packages/admin/components/api/hooks/useSchemaContext.ts
packages/admin/components/composed/collection/CollectionUpdateForm/CollectionUpdateForm.tsx
packages/admin/components/composed/community/CommunityUpdateForm/CommunityUpdateForm.tsx
packages/admin/components/composed/item/ItemUpdateForm/ItemUpdateForm.tsx

[B] Fix missing schema prop values on uncached detail forms

---

packages/admin/components/composed/contribution/ContributionCreateForm/ContributionCreateForm.tsx

[B] Remove required from contributor role (matches API)

---

packages/admin/__schema__/schema.json
packages/admin/components/composed/collection/CollectionList/CollectionList.tsx
packages/admin/components/composed/search/SearchResultList/SearchResultList.tsx
packages/admin/hooks/useSearchQueryVars.ts
packages/admin/locales/en.json
packages/admin/pages/collections/[slug]/collections.tsx
packages/admin/pages/collections/[slug]/items.tsx
packages/admin/pages/collections/index.tsx
packages/admin/pages/communities/[slug]/collections.tsx
packages/admin/pages/items/[slug]/items.tsx
packages/admin/pages/items/index.tsx
packages/admin/schema.graphql
packages/admin/types/graphql-schema.d.ts
packages/frontend/__schema__/schema.json
packages/frontend/components/composed/search/SearchHero/SearchHero.tsx
packages/frontend/components/composed/search/SearchResults/SearchResults.tsx
packages/frontend/lib/locales/en.json
packages/frontend/schema.graphql
packages/frontend/types/graphql-schema.d.ts

[B] Fix broken search on schema in admin

---

packages/admin/__generated__/EntityOrderingEditDrawerQuery.graphql.ts
packages/admin/components/api/SchemaInstanceForm/Properties/EntitiesProperty/EntitiesProperty.tsx
packages/admin/components/atomic/Pagination/Pagination.styles.ts
packages/admin/components/atomic/links/ImageLink/ImageLink.styles.ts
packages/admin/components/composed/model/ModelColumns/EntityThumbnailColumn/EntityThumbnailColumn.styles.ts
packages/admin/components/composed/ordering/EntityOrderingEditDrawer/EntityOrderingEditDrawer.tsx
packages/admin/components/forms/ContributorTypeahead/ContributorTypeahead.tsx
packages/admin/components/forms/EntitySelector/EntitySelectorController.tsx
packages/admin/components/forms/Multiselect/Multiselect.tsx
packages/admin/components/forms/OrderDefinitionSelect/OrderDefinitionSelect.tsx
packages/admin/components/forms/SchemaSelector/SchemaSelectorModal.tsx
packages/admin/components/layout/Grid/Grid.styles.ts
packages/admin/components/layout/Table/Table.styles.ts
packages/admin/locales/en.json

- Fix extra line after mobile lists, homepage list, thumbnail size
- Fix edit ordering drawer header
- Add placeholder text for multiselects
- Make sure node is not undefined

[B] Fix small bugs

---

packages/admin/components/api/SchemaFormFields/SchemaFormFields.tsx
packages/admin/components/api/SchemaInstanceForm/Factories/GroupProperty/GroupProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Factories/SchemaProperty/SchemaProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/EntitiesProperty/EntitiesProperty.tsx
packages/admin/components/api/SchemaInstanceForm/Properties/EntityProperty/EntityProperty.tsx
packages/admin/components/api/SchemaInstanceForm/SchemaInstanceProperty.tsx
packages/admin/components/forms/BaseArrayList/BaseArrayList.styles.ts
packages/admin/components/forms/Multiselect/Multiselect.tsx

[F] Add no options message to EntitiesProperty

---

packages/frontend/components/atomic/BaseDropdown/BaseDropdown.tsx
packages/frontend/components/atomic/Breadcrumbs/BreadcrumbLink.tsx
packages/frontend/components/atomic/Breadcrumbs/Breadcrumbs.tsx
packages/frontend/components/atomic/Dropdown/Dropdown.tsx
packages/frontend/components/atomic/Dropdown/DropdownLink/DropdownLink.tsx
packages/frontend/components/atomic/Dropdown/DropdownLink/index.ts
packages/frontend/components/composed/community/CommunityNavList/CommunityNavListContent.tsx
packages/frontend/components/composed/entity/EntityNavBar/EntityNavList/EntityNavList.tsx
packages/frontend/components/composed/entity/EntityOrderSelect/EntityOrderSelect.tsx
packages/frontend/components/composed/instance/CommunityPicker/CommunityPicker.tsx
packages/frontend/components/composed/viewer/AccountDropdown/AccountDropdown.tsx
packages/frontend/components/factories/IconFactory/IconFactory.tsx
packages/frontend/components/layout/BreadcrumbsBar/BreadcrumbsBar.tsx
packages/frontend/components/svgs/icons/X.tsx
packages/frontend/components/svgs/icons/index.ts
packages/frontend/lib/locales/en.json

[B] Close dropdown when link is clicked

---

packages/frontend/__generated__/collectionMetadataQuery.graphql.ts
packages/frontend/__generated__/communityMetadataQuery.graphql.ts
packages/frontend/__generated__/itemMetadataQuery.graphql.ts
packages/frontend/__generated__/orderingCollectionMetadataQuery.graphql.ts
packages/frontend/__generated__/orderingCommunityMetadataQuery.graphql.ts
packages/frontend/__generated__/pageCollectionMetadataQuery.graphql.ts
packages/frontend/__generated__/pageCommunityMetadataQuery.graphql.ts
packages/frontend/__generated__/pageItemPageMetadataQuery.graphql.ts
packages/frontend/__generated__/siteMetadataQuery.graphql.ts
packages/frontend/app/(frontend)/(pages)/_metadata/site.ts
packages/frontend/app/(frontend)/(pages)/collections/[slug]/_metadata/collection.ts
packages/frontend/app/(frontend)/(pages)/collections/[slug]/browse/[ordering]/_metadata/ordering.ts
packages/frontend/app/(frontend)/(pages)/collections/[slug]/browse/[ordering]/layout.tsx
packages/frontend/app/(frontend)/(pages)/collections/[slug]/layout.tsx
packages/frontend/app/(frontend)/(pages)/collections/[slug]/page/[page]/_metadata/page.ts
packages/frontend/app/(frontend)/(pages)/collections/[slug]/page/[page]/layout.tsx
packages/frontend/app/(frontend)/(pages)/communities/[slug]/_metadata/community.ts
packages/frontend/app/(frontend)/(pages)/communities/[slug]/browse/[ordering]/_metadata/ordering.ts
packages/frontend/app/(frontend)/(pages)/communities/[slug]/browse/[ordering]/layout.tsx
packages/frontend/app/(frontend)/(pages)/communities/[slug]/layout.tsx
packages/frontend/app/(frontend)/(pages)/communities/[slug]/page/[page]/_metadata/page.ts
packages/frontend/app/(frontend)/(pages)/communities/[slug]/page/[page]/layout.tsx
packages/frontend/app/(frontend)/(pages)/items/[slug]/_metadata/item.ts
packages/frontend/app/(frontend)/(pages)/items/[slug]/layout.tsx
packages/frontend/app/(frontend)/(pages)/items/[slug]/page/[page]/_metadata/page.ts
packages/frontend/app/(frontend)/(pages)/items/[slug]/page/[page]/layout.tsx
packages/frontend/app/(frontend)/(pages)/layout.tsx
packages/frontend/helpers/index.ts
packages/frontend/helpers/strings.ts
packages/frontend/types/page.d.ts

[B] Add metadata to frontend pages

---

packages/admin/__generated__/EntityPageUpdateFormMutation.graphql.ts
packages/admin/components/api/MutationForm/MutationForm.tsx
packages/admin/components/composed/pages/EntityPageUpdateForm/EntityPageUpdateForm.tsx
packages/admin/locales/en.json
packages/frontend/components/atomic/Markdown/patterns/PageMarkdown.tsx
packages/frontend/components/composed/article/ArticleHero/ArticleHero.tsx
packages/frontend/components/composed/community/CommunityPageLayout/CommunityPageLayout.tsx
packages/frontend/components/composed/entity/EntityPageLayout/EntityPageLayout.tsx
packages/frontend/components/layout/hero/PrimaryHero/PrimaryHero.tsx
packages/frontend/theme/utility/typography.ts
packages/lib/api/components/LazyLoadQueryWrapper.tsx

[B] Entity page body fixes

---

packages/admin/components/atomic/Breadcrumbs/Breadcrumbs.tsx
packages/admin/components/atomic/dropdown/Dropdown/Dropdown.styles.ts
packages/admin/components/atomic/dropdown/Dropdown/Dropdown.tsx
packages/admin/components/atomic/navs/TabNav/TabNav.tsx
packages/admin/components/composed/collection/CollectionLayout/CollectionLayout.tsx
packages/admin/components/composed/item/ItemLayout/ItemLayout.tsx
packages/admin/components/composed/search/SearchModal/SearchModal.styles.ts
packages/admin/components/forms/CollectionTypeahead/CollectionTypeahead.tsx
packages/admin/components/forms/ContributorTypeahead/ContributorTypeahead.tsx
packages/admin/components/forms/EntitySelector/EntityTypeahead/EntityTypeahead.tsx
packages/admin/components/forms/ItemTypeahead/ItemTypeahead.tsx
packages/admin/components/forms/LinkTargetTypeahead/LinkTargetTypeahead.tsx
packages/admin/components/forms/OrderDefinitionSelect/OrderDefinitionSelect.tsx
packages/admin/components/forms/RoleSelect/patterns/NodeRoleSelect.tsx
packages/admin/components/forms/UserTypeahead/UserTypeahead.tsx

Also resolves:
- MERU-991
- MERU-978
- MERU-980
- MERU-977

[B] Various admin UX improvements
